# Binary formula over the public Athanor releases (ADR 0026). Regenerated by
# the source repo's release workflow via scripts/gen_brew.sh — edits here are
# overwritten on the next release.
class Athanor < Formula
  desc "Web-based platform for managing agentic coding sessions"
  homepage "https://github.com/TranscendOfSypherus/athanor-releases"
  version "0.1.5"
  license :cannot_represent # free binaries, not open source — see the releases repo

  on_macos do
    on_arm do
      url "https://github.com/TranscendOfSypherus/athanor-releases/releases/download/v0.1.5/athanor-mac-arm64"
      sha256 "abe20d5e5c96bb8dc2bb50faa140c33f3d80590920f259de944086321aadf51d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TranscendOfSypherus/athanor-releases/releases/download/v0.1.5/athanor-linux-arm64"
      sha256 "7a4878c34ab4524a5143169d2fbdb02b0b62009279c276ff92bbabd328479d16"
    end
    on_intel do
      url "https://github.com/TranscendOfSypherus/athanor-releases/releases/download/v0.1.5/athanor-linux-x64"
      sha256 "b654e0ba01073df2a9b452dff1ec4d1e128e2f5032e2210c608dabf573475699"
    end
  end

  def install
    bin.install Dir["athanor-*"].first => "athanor"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/athanor --version")
  end
end
