# Binary formula over the public Athanor releases (ADR 0026). Regenerated by
# the source repo's release workflow via scripts/gen_brew.sh — edits here are
# overwritten on the next release.
class Athanor < Formula
  desc "Web-based platform for managing agentic coding sessions"
  homepage "https://github.com/TranscendOfSypherus/athanor-releases"
  version "0.1.2"
  license :cannot_represent # free binaries, not open source — see the releases repo

  on_macos do
    on_arm do
      url "https://github.com/TranscendOfSypherus/athanor-releases/releases/download/v0.1.2/athanor-mac-arm64"
      sha256 "c42dca150bab48da9e56722d501886696be28e7603096d6e2350bedcf829042d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TranscendOfSypherus/athanor-releases/releases/download/v0.1.2/athanor-linux-arm64"
      sha256 "09787703ddf99719f13c80a9aa3c93d5c67f170bae8b188acc005a43e73d756b"
    end
    on_intel do
      url "https://github.com/TranscendOfSypherus/athanor-releases/releases/download/v0.1.2/athanor-linux-x64"
      sha256 "36ed008ef4e8ffeff6dc2fd163800e7fe56aadeb7928bb5cdb10776d6b71d1ee"
    end
  end

  def install
    bin.install Dir["athanor-*"].first => "athanor"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/athanor --version")
  end
end
